### PR TITLE
Filling the ressourceNotFound boolean

### PR DESCRIPTION
**Pull request by RemiBou**
There is a property in LocalizedString for saying that the ressource was found or not

### CODE REVIEW

**Comment by damienbod** [comment]
super, thanks greetings Damien

**Comment by damienbod** [comment]
I'll create a new package with this as soon as possible

**Comment by damienbod** [comment]
https://www.nuget.org/packages/Localization.SqlLocalizer/1.0.8
thanks

**Comment by RemiBou** [comment]
thank you !

**Pull request merged**
